<a href="https://colab.research.google.com/github/gowthamich35/DataScienceZeotap/blob/main/Chunchu_Gowthami_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
cs = pd.read_csv('Customers.csv')
ps = pd.read_csv('Products.csv')
ts = pd.read_csv('Transactions.csv')

In [5]:
cs.info()
ps.info()
ts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    200 non-null    object
 1   CustomerName  200 non-null    object
 2   Region        200 non-null    object
 3   SignupDate    200 non-null    object
dtypes: object(4)
memory usage: 6.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ProductID    100 non-null    object
 1   ProductName  100 non-null    object
 2   Category     100 non-null    object
 3   Price        100 non-null    float64
dtypes: float64(1), object(3)
memory usage: 3.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    1000 non-null   object
 1   CustomerID       1000 non-null   object
 2   ProductID        1000 non-null   object
 3   TransactionDate  1000 non-null   object
 4   Quantity         1000 non-null   int64
 5   TotalValue       1000 non-null   float64
 6   Price            1000 non-null   float64
dtypes: float64(2), int64(1), object(4)
memory usage: 54.8+ KB

In [7]:
cs.isnull().sum()

CustomerID      0
CustomerName    0
Region          0
SignupDate      0
dtype: int64

In [8]:
ps.isnull().sum()

ProductID      0
ProductName    0
Category       0
Price          0
dtype: int64

In [9]:
ts.isnull().sum()

TransactionID      0
CustomerID         0
ProductID          0
TransactionDate    0
Quantity           0
TotalValue         0
Price              0
dtype: int64

In [13]:
cs.head()

  CustomerID        CustomerName         Region  SignupDate
0      C0001    Lawrence Carroll  South America  2022-07-10
1      C0002      Elizabeth Lutz           Asia  2022-02-13
2      C0003      Michael Rivera  South America  2024-03-07
3      C0004  Kathleen Rodriguez  South America  2022-10-09
4      C0005         Laura Weber           Asia  2022-08-15

In [14]:
ps.head()

  ProductID              ProductName     Category   Price
0      P001     ActiveWear Biography        Books  169.30
1      P002    ActiveWear Smartwatch  Electronics  346.30
2      P003  ComfortLiving Biography        Books   44.12
3      P004            BookWorld Rug   Home Decor   95.69
4      P005          TechPro T-Shirt     Clothing  429.31

In [15]:
ts.head()

,TransactionID,CustomerID,ProductID,TransactionDate,Quantity,TotalValue,Price
0,T00001,C0199,P067,2024-08-25 12:38:23,1,300.68,300.68
1,T00112,C0146,P067,2024-05-27 22:23:54,1,300.68,300.68
2,T00166,C0127,P067,2024-04-25 07:38:55,1,300.68,300.68
3,T00272,C0087,P067,2024-03-26 22:55:37,2,601.36,300.68
4,T00363,C0070,P067,2024-03-21 15:10:10,3,902.04,300.68

*Insight-1*

**The total number of unique customers is calculated by using the nunique() method on the CustomerID column of the customers.csv file. This method counts all distinct customer IDs, which gives us the overall customer base.**

In [11]:
#insight-1
#Total Number of Customers
total_customers = cs['CustomerID'].nunique()
print(f"Total Number of Customers: {total_customers}")

Total Number of Customers: 200

*Insight-2*

**To find the number of unique products sold, we use the nunique() method on the ProductID column from the transactions.csv file. This identifies how many different products are present in the transactions.**

In [12]:
#insight-2
#Number of Products Sold
unique_products_sold = ts['ProductID'].nunique()
print(f"Number of Products Sold: {unique_products_sold}")

Number of Products Sold: 100

*Insight-3*

**By using the idxmax() method, we identify the product with the highest price from the products.csv file. The method returns the index of the row with the maximum price, which we use to retrieve the product details.**

In [17]:
# 3. Most Expensive Product
most_expensive_product = ps.loc[ps['Price'].idxmax()]
print(f"Most Expensive Product: {most_expensive_product['ProductName']} with a price of {most_expensive_product['Price']} USD")

Most Expensive Product: TechPro Textbook with a price of 497.76 USD

*Insight-4*

**Using the groupby('CustomerID') method on the transactions.csv file, we group the data by customer, and then use size() to count the number of transactions (orders) for each customer.**

In [22]:
# Number of Orders per Customer
orders_per_customer = ts.groupby('CustomerID').size()
print(f"Number of Orders per Customer:")
print(orders_per_customer)

Number of Orders per Customer:
CustomerID
C0001    5
C0002    4
C0003    4
C0004    8
C0005    3
        ..
C0196    4
C0197    3
C0198    2
C0199    4
C0200    5
Length: 199, dtype: int64

*Insight-5*

**To find the customer who placed the most orders, we identify the CustomerID associated with the maximum value in the orders_per_customer series. We use orders_per_customer.max() to get the maximum order count, then filter to get the corresponding customer.**

In [23]:
#CustomerID with the maximum number of orders
max_orders_customer = orders_per_customer[orders_per_customer == orders_per_customer.max()]
print(f"Customer(s) with the Maximum Orders: {max_orders_customer}")

Customer(s) with the Maximum Orders: CustomerID
C0109    11
C0156    11
dtype: int64